# Generated by Django 2.0 on 2018-03-19 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=64, unique=True, verbose_name='主机名')),
                ('network_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='外网IP')),
                ('inner_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='内网IP')),
                ('system', models.CharField(blank=True, max_length=128, null=True, verbose_name='系统版本')),
                ('cpu', models.CharField(blank=True, max_length=64, null=True, verbose_name='CPU')),
                ('memory', models.CharField(blank=True, max_length=64, null=True, verbose_name='内存')),
                ('disk', models.CharField(blank=True, max_length=256, null=True, verbose_name='硬盘')),
                ('bandwidth', models.IntegerField(blank=True, default='1', null=True, verbose_name='带宽')),
                ('platform', models.CharField(choices=[('1', '阿里云'), ('2', 'AWS'), ('3', '其他')], max_length=128, verbose_name='平台')),
                ('region', models.CharField(choices=[('1', '华北2'), ('2', '香港'), ('3', '东京'), ('4', '其他')], max_length=256, verbose_name='区域')),
                ('manager', models.CharField(choices=[('1', '何全'), ('2', '其他')], max_length=128, verbose_name='负责人')),
                ('project', models.CharField(choices=[('1', '项目1'), ('2', '项目2'), ('3', '项目3'), ('其他', '其他')], max_length=128, verbose_name='项目')),
                ('Instance_id', models.CharField(blank=True, max_length=64, null=True, verbose_name='实例ID')),
                ('ctime', models.DateTimeField(verbose_name='购买时间')),
                ('utime', models.DateTimeField(verbose_name='到期时间')),
                ('ps', models.CharField(blank=True, max_length=1024, null=True, verbose_name='备注')),
                ('is_active', models.BooleanField(default=True, verbose_name='激活')),
            ],
            options={
                'verbose_name': '资产管理',
                'verbose_name_plural': '资产管理',
                'db_table': 'asset',
                'permissions': {('read_asset', '只读资产管理')},
            },
        ),
        migrations.CreateModel(
            name='platform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': '云平台管理',
                'verbose_name_plural': '云平台管理',
                'db_table': 'platform',
            },
        ),
        migrations.CreateModel(
            name='region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('platforms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset.platform')),
            ],
            options={
                'verbose_name': '云区域管理',
                'verbose_name_plural': '云区域管理',
                'db_table': 'region',
            },
        ),
    ]
