# Generated by Django 2.0.3 on 2018-03-17 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='project',
            field=models.CharField(choices=[('项目1', '项目1'), ('项目2', '项目2'), ('项目3', '项目3'), ('其他', '其他')], default=1, max_length=128, verbose_name='负责人'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='asset',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='激活'),
        ),
    ]
