# Generated by Django 2.0 on 2018-03-16 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='manager',
            field=models.CharField(choices=[('何全', '何全'), ('其他', '其他')], default=1, max_length=128, verbose_name='负责人'),
            preserve_default=False,
        ),
    ]
