# Generated by Django 2.0 on 2018-03-19 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='manager',
            field=models.CharField(choices=[('何全', '何全'), ('其他', '其他')], max_length=128, verbose_name='负责人'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='platform',
            field=models.CharField(choices=[('阿里云', '阿里云'), ('AWS', 'AWS'), ('其他', '其他')], max_length=128, verbose_name='平台'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='project',
            field=models.CharField(choices=[('项目1', '项目1'), ('项目2', '项目2'), ('项目3', '项目3'), ('其他', '其他')], max_length=128, verbose_name='项目'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='region',
            field=models.CharField(choices=[('华北2', '华北2'), ('香港', '香港'), ('东京', '东京'), ('其他', '其他')], max_length=256, verbose_name='区域'),
        ),
    ]
