# Generated by Django 2.0.3 on 2018-03-18 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0002_auto_20180317_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='project',
            field=models.CharField(choices=[('项目1', '项目1'), ('项目2', '项目2'), ('项目3', '项目3'), ('其他', '其他')], max_length=128, verbose_name='项目'),
        ),
    ]
