# Generated by Django 2.0.3 on 2018-03-20 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0003_auto_20180320_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='platform',
            field=models.CharField(choices=[('阿里云', '阿里云'), ('AWS', 'AWS')], default=1, max_length=128, verbose_name='平台'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='asset',
            name='region',
            field=models.CharField(choices=[('阿里云', '华北2'), ('阿里云', '香港'), ('AWS', '东京'), ('AWS', '美国')], max_length=128, verbose_name='区域'),
        ),
    ]
