# Generated by Django 2.0.3 on 2018-03-18 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0004_asset_import'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset_import',
            name='file',
            field=models.FileField(upload_to='assets/%Y%m%d95687', verbose_name='文件'),
        ),
    ]
