# Generated by Django 2.0.3 on 2018-03-18 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0005_auto_20180318_1208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset_import',
            name='file',
        ),
        migrations.AddField(
            model_name='asset_import',
            name='uploadFile',
            field=models.FileField(default=1, upload_to='disk/upload/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asset_import',
            name='userName',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
