# Generated by Django 2.0 on 2018-03-23 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0006_auto_20180320_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='password',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='密码'),
        ),
        migrations.AddField(
            model_name='asset',
            name='private_key',
            field=models.TextField(blank=True, max_length=4096, null=True, verbose_name='私钥'),
        ),
        migrations.AddField(
            model_name='asset',
            name='user',
            field=models.CharField(blank=True, default='root', max_length=64, null=True, verbose_name='登录用户名'),
        ),
    ]
