# Generated by Django 2.0.3 on 2018-03-18 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0006_auto_20180318_1222'),
    ]

    operations = [
        migrations.DeleteModel(
            name='asset_import',
        ),
    ]
