# Generated by Django 2.0.3 on 2018-03-23 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0007_auto_20180323_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='ctime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='购买时间'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='utime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='到期时间'),
        ),
    ]
