# Generated by Django 2.0 on 2018-03-24 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0008_auto_20180323_2223'),
    ]

    operations = [
        migrations.CreateModel(
            name='asset_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, default='root', max_length=64, null=True, verbose_name='登录用户名')),
                ('password', models.CharField(blank=True, max_length=256, null=True, verbose_name='密码')),
                ('private_key', models.TextField(blank=True, max_length=4096, null=True, verbose_name='私钥')),
            ],
            options={
                'verbose_name': '资产用户',
                'verbose_name_plural': '资产用户',
                'db_table': 'asset_user',
                'permissions': {('read_asset_user', '只读资产用户')},
            },
        ),
        migrations.RemoveField(
            model_name='asset',
            name='password',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='private_key',
        ),
        migrations.AlterField(
            model_name='asset',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='asset.asset_user', verbose_name='登录用户'),
        ),
    ]
