# Generated by Django 2.0 on 2018-03-24 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0009_auto_20180324_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='buy_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='购买时间'),
        ),
        migrations.AddField(
            model_name='asset',
            name='expire_utime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='到期时间'),
        ),
        migrations.AddField(
            model_name='asset_user',
            name='ctime',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='asset_user',
            name='ps',
            field=models.CharField(blank=True, max_length=10240, null=True, verbose_name='备注'),
        ),
        migrations.AddField(
            model_name='asset_user',
            name='utime',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='ctime',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='utime',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='asset_user',
            name='private_key',
            field=models.FileField(blank=True, null=True, upload_to='upload/private_key/%Y%m%d44743', verbose_name='文件'),
        ),
    ]
