# Generated by Django 2.0 on 2018-03-24 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0010_auto_20180324_1604'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='expire_utime',
            new_name='expire_time',
        ),
        migrations.AlterField(
            model_name='asset_user',
            name='private_key',
            field=models.FileField(blank=True, null=True, upload_to='upload/private_key/%Y%m%d79302', verbose_name='文件'),
        ),
    ]
