# Generated by Django 2.0 on 2018-03-24 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0011_auto_20180324_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='buy_time',
            field=models.DateTimeField(null=True, verbose_name='购买时间'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='expire_time',
            field=models.DateTimeField(null=True, verbose_name='到期时间'),
        ),
        migrations.AlterField(
            model_name='asset_user',
            name='private_key',
            field=models.FileField(blank=True, null=True, upload_to='upload/private_key/%Y%m%d16585', verbose_name='文件'),
        ),
    ]
