# Generated by Django 2.0 on 2018-03-24 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0012_auto_20180324_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='port',
            field=models.IntegerField(blank=True, default='22', null=True, verbose_name='登录端口'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='buy_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='购买时间'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='expire_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='到期时间'),
        ),
        migrations.AlterField(
            model_name='asset_user',
            name='private_key',
            field=models.FileField(blank=True, null=True, upload_to='upload/private_key/%Y%m%d91927', verbose_name='文件'),
        ),
    ]
