# Generated by Django 2.0 on 2018-03-24 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0014_auto_20180324_1631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset_user',
            name='hostname',
        ),
        migrations.AlterField(
            model_name='asset_user',
            name='private_key',
            field=models.FileField(blank=True, null=True, upload_to='upload/private_key/%Y%m%d68479', verbose_name='私钥'),
        ),
    ]
