# Generated by Django 2.0 on 2018-03-24 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0015_auto_20180324_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset_user',
            name='hostname',
            field=models.CharField(default=1, max_length=64, unique=True, verbose_name='名称'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='asset_user',
            name='private_key',
            field=models.FileField(blank=True, null=True, upload_to='upload/private_key/%Y%m%d35249', verbose_name='私钥'),
        ),
    ]
