FROM   centos:7
MAINTAINER   hequan   hequan2011@sina.com


RUN  yum   update    -y && \
     yum   install   iproute wget git  net-tools  gcc automake autoconf libtool make gcc gcc-c++   zlib*  python-devel mysql-devel zlib-devel openssl-devel  sqlite-devel  -y

WORKDIR  /usr/local/src
RUN  wget http://mirrors.sohu.com/python/3.6.5/Python-3.6.5.tgz  && tar xf Python-3.6.5.tgz
WORKDIR /usr/local/src/Python-3.6.5/


RUN ./configure   --enable-shared --enable-loadable-sqlite-extensions --with-zlib   && \
    make  -j  4  && make install  && \
    rm -rf /usr/bin/python   && \
    ln -s /usr/local/bin/python3.6    /usr/bin/python && \
    sed  -i    's/\#\!\/usr\/bin\/python/\#\!\/usr\/bin\/python2/'   /usr/bin/yum   && \
    sed  -i    's/\#\! \/usr\/bin\/python/\#\! \/usr\/bin\/python2/'   /usr/libexec/urlgrabber-ext-down  && \
    echo  "/usr/local/lib"  >> /etc/ld.so.conf  && \
    /sbin/ldconfig && \
    mkdir  -p  /root/.pip/ && \
    echo "[global]" >  /root/.pip/pip.conf  && \
    echo "trusted-host=mirrors.aliyun.com"  >>  /root/.pip/pip.conf  && \
    echo "index-url=http://mirrors.aliyun.com/pypi/simple/"  >>  /root/.pip/pip.conf && \
    python -V  && \
    rm -rf  /usr/local/src/Python-3.6.5*


WORKDIR  /opt/
ENTRYPOINT   ["/bin/bash"]