FROM   python3.6.5
MAINTAINER   hequan   hequan2011@sina.com

ARG  ip="127.0.0.1"

WORKDIR  /tmp
RUN  wget https://mirrors.tuna.tsinghua.edu.cn/epel/epel-release-latest-7.noarch.rpm  && \
     rpm -ivh epel-release-latest-7.noarch.rpm   && \
     yum  install supervisor  bzip2 sshpass  net-tools -y  && \
     mkdir  /etc/ansible/

RUN  wget https://files.pythonhosted.org/packages/12/2a/e9e4fb2e6b2f7a75577e0614926819a472934b0b85f205ba5d5d2add54d0/Twisted-18.4.0.tar.bz2  && \
    tar xf Twisted-18.4.0.tar.bz2

WORKDIR /tmp/Twisted-18.4.0

RUN  python3 setup.py install

COPY    chain  /opt/chain

WORKDIR   /opt/chain/

RUN  python -m pip  install --upgrade pip

RUN  python -m pip  install -r   requirements.txt  && \
     python     manage.py   makemigrations  && \
     python     manage.py   migrate

COPY  password.sh  /tmp/password.sh

RUN   sed  -i "s/^web_ssh.*$/web_ssh = '${ip}' /g"  /opt/chain/chain/settings.py   && \
      sh /tmp/password.sh  && \
      mkdir -p /etc/supervisor/

COPY  supervisord.conf   /etc/supervisor/supervisord.conf

RUN  sed  -i    's/\#\!\/usr\/bin\/python/\#\!\/usr\/bin\/python2/'   /usr/bin/supervisord  && \
     sed  -i    's/\#\!\/usr\/bin\/python/\#\!\/usr\/bin\/python2/'   /usr/bin/supervisorctl

EXPOSE  8001 8002

USER  root
ENTRYPOINT   supervisord -c /etc/supervisor/supervisord.conf