FROM   python3.6.5
MAINTAINER   hequan   hequan2011@sina.com



WORKDIR  /tmp
RUN    wget https://mirrors.tuna.tsinghua.edu.cn/epel/epel-release-latest-7.noarch.rpm
RUN    rpm -ivh epel-release-latest-7.noarch.rpm

RUN     yum  install supervisor    net-tools -y

WORKDIR  /opt/

#RUN  git clone https://github.com/hequan2017/chain.git
COPY    chain  /opt/chain
WORKDIR  /opt/chain/
RUN   python -m pip  install -r   requirements.txt


RUN mkdir -p /etc/supervisor/


COPY  supervisord.conf   /etc/supervisor/supervisord.conf

RUN   sed  -i    's/\#\!\/usr\/bin\/python/\#\!\/usr\/bin\/python2/'   /usr/bin/supervisord
RUN   sed  -i    's/\#\!\/usr\/bin\/python/\#\!\/usr\/bin\/python2/'   /usr/bin/supervisorctl

EXPOSE  8001 8002
USER  root
ENTRYPOINT   supervisord -c /etc/supervisor/supervisord.conf